name: airfoilGNN
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - numpy=1.24.3
  - pandas=2.0.1
  - matplotlib=3.7.1
  - plotly=5.14.1
  - pytorch=2.0.1
  - pyg=2.3.0  # For torch_geometric
  - streamlit=1.22.0
  - pip:
    - torch-geometric==2.3.0
    - streamlit-plotly-events==0.0.6