name: airfoilGNN
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=24.2
  - pip:
    - matplotlib==3.9.2
    - numpy==2.1.0
    - pandas==2.2.2
    - plotly==6.1.2
    - lightning
    - scipy==1.14.1
    - streamlit==1.46.0
    - scikit-learn==1.5.1
    - torch==2.4.0
    - torch-geometric==2.5.3
    - torchaudio==2.4.0
    - torchinfo==1.8.0
    - torchmetrics==1.4.1
    - torchsummary==1.5.1
    - torchvision==0.19.0
    - tqdm==4.66.5