name: airfoilGNN
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=24.2
  - pip:
    - matplotlib==3.9.2
    - numpy==2.1.0
    - pandas==2.2.2
    - plotly==6.1.2
    - lightning
    - scipy==1.14.1
    - streamlit==1.46.0
    - scikit-learn==1.5.1
    - torch
    - torch-geometric
    - torchaudio
    - torchinfo
    - torchmetrics
    - torchsummary
    - torchvision
    - tqdm