name: torch-lightning
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - boltons=24.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cffi=1.17.1
  - colorama=0.4.6
  - comm=0.2.2
  - conda=23.9.0
  - conda-devenv=3.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cryptography=44.0.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jsonpatch=1.33
  - jsonpointer=2.0
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=18.1.8
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libsodium=1.0.18
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - prompt-toolkit=3.0.47
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycosat=0.6.6
  - pycparser=2.22
  - pygments=2.18.0
  - pyopenssl=25.0.0
  - pysocks=1.7.1
  - python=3.10.14
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.32.3
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.8
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - truststore=0.10.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.1
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - alembic==1.14.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - colorlog==6.9.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - filelock==3.15.4
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - idna==3.8
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lightning==2.4.0
      - lightning-utilities==0.11.6
      - mako==1.3.8
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.3
      - numpy==2.1.0
      - optuna==4.2.0
      - pandas==2.2.2
      - pdf2image==1.17.0
      - pillow==10.4.0
      - point-cloud-utils==0.31.0
      - protobuf==5.28.3
      - psutil==6.0.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - pytz==2024.1
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - sqlalchemy==2.0.37
      - sympy==1.13.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - tikz-python==0.0.4
      - torch==2.4.0
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2
      - torchaudio==2.4.0
      - torchinfo==1.8.0
      - torchmetrics==1.4.1
      - torchsummary==1.5.1
      - torchvision==0.19.0
      - tqdm==4.66.5
      - tzdata==2024.1
      - urllib3==2.2.2
      - webcolors==24.11.1
      - yarl==1.9.4
