name: airfoilGNN
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1
  - appnope=0.1.4
  - asttokens=2.4.1
  - blosc=1.21.6
  - boltons=24.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.2.25
  - cairo=1.18.4
  - cffi=1.17.1
  - colorama=0.4.6
  - comm=0.2.2
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cryptography=44.0.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - double-conversion=3.3.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.4
  - ffmpeg=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeimage=3.18.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gl2ps=1.4.2
  - glew=2.1.0
  - gmp=6.3.0
  - graphite2=1.3.13
  - h2=4.2.0
  - harfbuzz=10.4.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - imath=3.1.12
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jasper=4.2.5
  - jedi=0.19.1
  - jsoncpp=1.9.6
  - jsonpatch=1.33
  - jsonpointer=2.0
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jxrlib=1.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libass=0.17.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.8
  - libclang13=18.1.8
  - libcurl=8.12.1
  - libcxx=18.1.8
  - libdeflate=1.23
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.82.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.23.1
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm18=18.1.8
  - liblzma=5.6.4
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopenvino=2025.0.0
  - libopenvino-arm-cpu-plugin=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.3.1
  - libpng=1.6.47
  - libpq=17.4
  - libprotobuf=5.28.3
  - libraw=0.21.4
  - librsvg=2.58.4
  - libsodium=1.0.18
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libusb=1.0.27
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.6
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=20.1.2
  - loguru=0.7.2
  - lz4-c=1.10.0
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - msgpack-python=1.1.0
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - occt=7.9.0
  - openexr=3.3.3
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - packaging=24.1
  - pango=1.56.1
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - pixman=0.44.2
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - pooch=1.8.2
  - proj=9.5.1
  - prompt-toolkit=3.0.47
  - propcache=0.3.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pure_eval=0.2.3
  - pycosat=0.6.6
  - pycparser=2.22
  - pygments=2.18.0
  - pyopenssl=25.0.0
  - pysocks=1.7.1
  - python=3.10.13
  - python_abi=3.10
  - pythonocc-core=7.9.0
  - pyvista=0.45.0
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qhull=2020.2
  - qt6-main=6.8.2
  - rapidjson=1.1.0.post20240409
  - readline=8.2
  - requests=2.32.3
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.8
  - scooby=0.10.0
  - sdl2=2.32.50
  - sdl3=3.2.8
  - setuptools=72.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.49.1
  - stack_data=0.6.2
  - svgwrite=1.4.3
  - svt-av1=3.0.0
  - tbb=2022.0.0
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - truststore=0.10.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - unicodedata2=16.0.0
  - utfcpp=4.0.6
  - vtk=9.3.1
  - vtk-base=9.3.1
  - vtk-io-ffmpeg=9.3.1
  - wcwidth=0.2.13
  - wheel=0.43.0
  - wslink=2.3.3
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.1
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aerosandbox==4.2.8
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - alembic==1.14.1
      - altair==5.5.0
      - anytree==2.13.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - blinker==1.9.0
      - build123d==0.9.1
      - cachetools==5.5.2
      - cadquery-ocp==7.8.1.1.post1
      - casadi==3.7.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.8
      - colorlog==6.9.0
      - contourpy==1.2.1
      - dill==0.4.0
      - ezdxf==1.4.1
      - filelock==3.15.4
      - flask==3.1.0
      - flask-sock==0.7.0
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h11==0.14.0
      - idna==3.8
      - imagesize==1.4.1
      - ipywidgets==8.1.6
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-console==6.6.3
      - jupyterlab-widgets==3.0.14
      - kiwisolver==1.4.5
      - lightning==2.4.0
      - lightning-utilities==0.11.6
      - mako==1.3.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - meshio==5.3.5
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - narwhals==1.42.1
      - networkx==3.3
      - neuralfoil==0.3.2
      - numpy==2.1.0
      - ocp-tessellate==3.0.11
      - ocp-vscode==2.7.1
      - ocpsvg==0.5.0
      - optuna==4.2.0
      - orjson==3.10.16
      - pandas==2.2.2
      - pdf2image==1.17.0
      - pillow==10.4.0
      - plotly==6.1.2
      - point-cloud-utils==0.31.0
      - protobuf==5.28.3
      - psutil==6.0.0
      - py-lib3mf==2.3.1
      - pyaml==25.1.0
      - pyarrow==20.0.0
      - pydeck==0.9.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - pytz==2024.1
      - referencing==0.36.2
      - rich==14.0.0
      - rpds-py==0.25.1
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - simple-websocket==1.1.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.37
      - streamlit==1.46.0
      - svgelements==1.9.6
      - svgpathtools==1.6.1
      - sympy==1.13.2
      - tenacity==9.1.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - tikz-python==0.0.4
      - toml==0.10.2
      - torch==2.4.0
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2
      - torchaudio==2.4.0
      - torchinfo==1.8.0
      - torchmetrics==1.4.1
      - torchsummary==1.5.1
      - torchvision==0.19.0
      - tqdm==4.66.5
      - trame==3.8.2
      - trame-client==3.7.1
      - trame-components==2.4.2
      - trame-server==3.4.0
      - trame-vtk==2.8.15
      - trame-vuetify==3.0.1
      - trianglesolver==1.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - webcolors==24.8.0
      - websockets==13.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wsproto==1.2.0
      - yarl==1.9.4
